export const projects = [
  {
    title: 'Music Prediction - ML',
    description: "Using Decision Tree Classifier, I implemented a Machine Learning algorithm that predicts the genre of music a person would most likely listen to based on their gender and age. This gives a general idea on how websites like Spotify and Youtube recommend music to users.",
      image: '/images/ML1.jpg',
      tags: ['AI ', ' Machine Learning', 'Python'],
    source: 'https://youtu.be/7eh4d6sabA0',
    visit: 'https://colab.research.google.com/drive/11C5dm1gb9p-ozogd-IkA9G4Iy9dXKQC1?usp=sharing',
    id: 0,
  },
  {
    title: 'COVID Care tech',
    description:"Won Best Mobile App in Neohacks'21 hackathon. It's a solution to mental health problems & isolation using Figma and Android studio. It has 3 sections: Find the closest Pharmacy & Therapist and an anon chat section.",
    image: '/images/covidcaretech.png',
    tags: ['Android Studio', 'Figma'],
    source: 'https://devpost.com/software/covid-care-tech',
    visit: 'https://github.com/Anass-ABEA/covid-care-tech.git',
    id: 1,
  },
  {
    title: 'Virtual Assistant in Python',
    description: "Using Python libraries, I built a virtual assistant that performs basic tasks such as giving its user the current time, playing a video on youtube, searching who a person is on Wikipedia, generating random jokes & other specifics (my favorite ice cream flavor, etc).",
      image: '/images/aialexa.png',
      tags: ['AI', 'Python'],
    source: 'https://youtu.be/AWvsXxDtEkU',
    visit: 'https://github.com/ghitabouzian/Virtual-Assistant.git',
    id: 2,
  },
  {
    title: 'Data Processing in R language',
    description: "Using R language, I processed Human Resources data in Rstudio. I made different graphs: pie charts and bar graphs. This was during my internship at ECS informatique; my internship report can be found down below.",
    image: '/images/data.png',
    tags: ['R', 'Graphs', 'Data Processing'],
    source: 'https://docs.google.com/document/d/1ckseSL9tZYswATYSOCqCN_tSD_A-BXVQ/edit?usp=sharing&ouid=115550977152446858481&rtpof=true&sd=true',
    visit: 'https://docs.google.com/document/d/1ckseSL9tZYswATYSOCqCN_tSD_A-BXVQ/edit?usp=sharing&ouid=115550977152446858481&rtpof=true&sd=true',
    id: 3,
  },
  {
    title: 'Ahram Juniors website',
    description: "Made a website for the nonprofit I founded Ahram Juniors.",
    image: '/images/aj.png',
    tags: ['Bootstrap', 'Web Development'],
    source: 'https://colorlib.com/',
    visit: 'https://ahramjuniors.github.io/',
    id: 4,
  },
  {
    title: 'Discrete Mathematics',
    description: "Learned about Discrete Math & wrote a blog about it (focus on Graph Theory).",
    image: '/images/gth.png',
    tags: ['Discrete Math', "Blog"],
    source: 'https://docs.google.com/document/d/1OZyHREBywRuTvW-DNJsFfY0Qr2SZpZRXLkab8ILeiFs/edit?usp=sharing',
    visit: 'https://docs.google.com/document/d/1OZyHREBywRuTvW-DNJsFfY0Qr2SZpZRXLkab8ILeiFs/edit?usp=sharing',
    id: 5,
  },
  {
    title: 'Art Portfolio',
    description: "You can check out my paintings by clicking on source!",
    image: '/images/paint.png',
    tags: ['Art'],
    source: 'https://docs.google.com/presentation/d/1op2zP00aYXHm8YReh6ZnQrJWHeEqGM7dbreyHiPrSYI/edit?usp=sharing',
    visit: 'https://docs.google.com/presentation/d/1op2zP00aYXHm8YReh6ZnQrJWHeEqGM7dbreyHiPrSYI/edit?usp=sharing',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey: learned Python and HTML&CSS', },
  { year: 2020, text: 'Worked on team projects in CS', },
  { year: 2020, text: 'Won Injaz Al Maghrib Innovation Camp', },
  { year: 2021, text: 'Founded Ahram Juniors', },
  { year: 2021, text: 'Won my 1st hackathon', },
  { year: 2021, text: 'Started doing AI projects', },
];